# Generated by Django 4.1.7 on 2023-03-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='status',
            field=models.CharField(default='order placed', max_length=20),
        ),
    ]
