# Generated by Django 4.1.7 on 2023-03-04 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('account_no', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('s_acholdername', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('s_pic', models.ImageField(upload_to='reseller/')),
                ('s_status', models.CharField(default='pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(default='', max_length=40)),
                ('p_name', models.CharField(max_length=30)),
                ('p_number', models.BigIntegerField()),
                ('p_details', models.CharField(max_length=300)),
                ('p_price', models.BigIntegerField()),
                ('p_stock', models.FloatField(default=0)),
                ('p_image', models.ImageField(upload_to='product/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller_app.reseller')),
            ],
        ),
    ]
